import React from 'react'
import type { Metadata, Viewport } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

import Provider from '@/components/Providers'
import BackgrounImage from '@/components/BackgrounImage'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    minimumScale: 1,
    maximumScale: 5,
    userScalable: false,
}

export default async function RootLayout({ children }: Readonly<React.PropsWithChildren>): Promise<React.ReactElement> {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={cn(GeistSans.className)}>
                <Provider attribute='class' defaultTheme='system' enableSystem>
                    <BackgrounImage />
                    {children}
                </Provider>
            </body>
        </html>
    )
}
